package lzham

const (
	LZHAM_Z_DEFLATED = 8
	LZHAM_Z_LZHAM    = 14

	LZHAM_Z_VERSION         = "10.8.1"
	LZHAM_Z_VERNUM          = 0xA810
	LZHAM_Z_VER_MAJOR       = 10
	LZHAM_Z_VER_MINOR       = 8
	LZHAM_Z_VER_REVISION    = 1
	LZHAM_Z_VER_SUBREVISION = 0
)
